### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by imhilla**
This project consisted of embedding video and images to look like that of YouTube video player. I used HTML and CSS only. I completed it alone. partner quit after two days.

### CODE REVIEW

**Review by davidmrtz-dev — CHANGES_REQUESTED** [review]
## Hi @imhilla  . 👨‍🚀  
### Very good job so far.
However, the following issues need to be fixed before moving on  👨‍💻  ⬇️   ⬇️ 
****
- [ ] Html Validator.
The validator listed some issues.
Please check the issues and fix that. 😄 👨‍💻 

Screen Shot 2020-03-28 at 3 10 26 PM

****
- [ ] Inline styling.
It is not allowed inline styling because it's considered a bad practice, instead use classes. 😄 
Please read this article where talks about good [coding practices](https://speckyboy.com/good-bad-css-practices) and why to use it. 
Screen Shot 2020-03-28 at 3 16 06 PM
****
- [ ] Side Bar. 
Very good job with your sidebar it looks awesome, but we can improve it adding some spacing between the video preview and text in order to make it looks as similar as possible to the page on which the project is based.
Also, please use an 'h' on the title of the video and make it bold to make it stand out. 
How it looks now. ⬇️ 

Screen Shot 2020-03-28 at 3 20 38 PM

The example on which the project is based. ⬇️ 

Screen Shot 2020-03-28 at 3 21 10 PM

****
### Optional.
****
- [ ] Use 'main' tag.
We encourage the use of the <main> tag for the dominant content of the <body> of a document.
****

### **Please kindly make the changes required and submit for re-review once you are ready!** 🙏 

****

### Status: Changes required. ♻️  👀 
****

Happy coding! 😄 💻  

**[TSE:  David Elí]** 👨‍💻 
Slack: @ David Eli Martinez Garcia

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello team! 

Great work implementing the requested changes! 🎖  However there are still some issues!

## Required changes

- [ ] Please be sure to follow code good practices on your CSS file. Right now there are repeated rules, like for example `display: flex` is used 12 times. Lets clean the file up. (Not only that rule is repeated there are many)

- [ ] Again on your CSS you are using ID's for styling, please remove the use of ID's and use classes only.

## Help

You can read this articles if you need a deeper understanding as to why the changes are required:

https://speckyboy.com/good-bad-css-practices/
https://www.quora.com/Why-is-it-considered-bad-form-to-use-an-ID-selector-in-a-CSS-stylesheet

After making the changes please re-submit your project for another review! 

Happy coding! 👍 

## Code review by Mario Enrique Delgado Naranjo

**Comment by uryelah** [comment]
Hello **Hillary Odhiambo**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**First of all, welcome to Microverse and good job working on the changes of your first project🌟**

Your project is almost good to go, you are just missing one requirement. You got this! 💪

---------    

## Required Changes 🏗 

- It seems that while fixing the last code review issues some new bugs appeared.

- [ ] Make sure to fix the text overlapping bug in the recommended videos area.
- [ ] Add some margin between the video and the recommended thumbnails.
Screenshot_2020-03-30 Microverse HTML CSS Project 1
**Original version for comparison:**
Screenshot_2020-03-30 Contributing to Open Source Part I The Easy Way

----

- [ ] [OPTIONAL] In the original page the recommended videos and their titles link you the videos, changing your cursor to a pointer, make the titles links and/or change the `cursor` property they have so they look clickable on hover.
------

**Kindly fix the REQUIRED issues and send another code review request.**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by imhilla** [comment]
Hello, code reviewers, while doing the work I used explorer to customize my CSS and not google chrome. Looks good here.
Here's a screenshot.
youtube
What should I do next.

**Comment by uryelah** [comment]
Hello Hillary, since it's your first project and the page contains all of the required elements I'll approve the project.

But from now on make sure to use either Chrome or Firefox to make your projects, most developers use those browsers and what they support is significantly different to what IE supports.

Take a look [at this Dev.to thread ](https://dev.to/mraza007/do-you-prefer-chrome-or-firefox-quantum-2a43)if you are unsure of which browser to choose for your next projects.


------
## Your project is approved! 🎊 🥅 💛 
### 
**You may close this Pull Request and merge the changes**

-------

**Keep being an awesome dev and good luck with your next project!**

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Pull request merged**
